### ISSUE TITLE
Append specific size

### ISSUE THREAD

**Issue by Marhc** [alexcrist/scrape-google-photos#1]
https://github.com/alexcrist/scrape-google-photos/blob/44126574ecab30b59653cbd2e7421999d48cb0c0/index.js#L58

Hi, Alex. 
Append specific size to get High Quality photos like '=w1920-h1080' to FullHD max resolution.

**Comment by Marhc** [comment]
The right line:
      content += '  ' + '\\'' + photo + '=w1920-h1080\\'';

Instead this:
https://github.com/alexcrist/scrape-google-photos/blob/44126574ecab30b59653cbd2e7421999d48cb0c0/index.js#L57

**Comment by alexcrist** [comment]
Cool deal. Thanks for opening the PR for this: https://github.com/alexcrist/scrape-google-photos/pull/2
